name: CI

on:
  push:
    branches: [ main, develop, rework ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    
    steps:
    - name: Checkout コード
      uses: actions/checkout@v4
    
    - name: Node.js ${{ matrix.node-version }} セットアップ
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: 依存関係インストール
      run: npm ci
    
    - name: 型チェック
      run: npm run typecheck
    
    - name: リンティング
      run: npm run lint
    
    - name: フォーマットチェック
      run: npm run format:check
    
    - name: テスト実行
      run: npm test
    
    - name: テストカバレッジ
      run: npm run test:coverage
    
    - name: ビルド
      run: npm run build
    
    - name: ビルド成果物のアップロード
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: dist/
        retention-days: 7

  security-audit:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout コード
      uses: actions/checkout@v4
    
    - name: Node.js セットアップ
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: 依存関係インストール
      run: npm ci
    
    - name: セキュリティ監査
      run: npm audit --audit-level=moderate
    
    - name: 脆弱性スキャン
      uses: ossf/scorecard-action@v2.3.1
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true
      continue-on-error: true
    
    - name: SARIF結果のアップロード
      if: always()
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: results.sarif

  quality-gate:
    runs-on: ubuntu-latest
    needs: [test, security-audit]
    if: always()
    
    steps:
    - name: 品質ゲート確認
      run: |
        if [[ "${{ needs.test.result }}" != "success" ]]; then
          echo "❌ テストが失敗しました"
          exit 1
        fi
        
        if [[ "${{ needs.security-audit.result }}" != "success" ]]; then
          echo "⚠️ セキュリティ監査で問題が検出されましたが、継続します"
        fi
        
        echo "✅ 品質ゲートを通過しました"