name: Dependency Review

on:
  pull_request:
    branches: [ main, develop ]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout コード
      uses: actions/checkout@v4
    
    - name: 依存関係レビュー
      uses: actions/dependency-review-action@v4
      with:
        # 深刻度がモデレート以上の脆弱性でフェイル
        fail-on-severity: moderate
        # ライセンス許可リスト（これ以外のライセンスは自動的に拒否される）
        allow-licenses: MIT, Apache-2.0, BSD-2-Clause, BSD-3-Clause, ISC, 0BSD, Python-2.0, Unlicense, CC0-1.0
        # コメントの設定
        comment-summary-in-pr: always
        # 依存関係変更の詳細表示
        show-openssf-scorecard: false
        warn-only: false